name: gerafoto_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  firebase_core: ^0.5.1
  html: ^0.14.0+3
  data: ^0.2.0
  flutter_js: ^0.2.2+0

  provider: ^4.0.5+1

  flutter_focus_watcher: ^0.0.1
  flutter_device_type: ^0.2.0
  firestore_ui: ^1.11.0
  firestore_cache: ^0.2.0
  firebase_auth: ^0.18.2
  cloud_firestore: ^0.14.2
  font_awesome_flutter: ^8.10.0
  firebase_storage: ^5.0.0
  time: ^1.3.0
  dependencies:
  # Newly reworked plugins covered by this migration guide:
  firebase_crashlytics: ^0.2.2
  cloud_functions: ^0.7.0
  firebase_messaging: ^8.0.0-dev.6
  # Updated to work with new core only plugins (no new changes):
  firebase_admob: ^0.10.1
  firebase_analytics: ^6.1.0
  firebase_database: ^4.2.0
  firebase_dynamic_links: ^0.6.1
  firebase_in_app_messaging: ^0.2.1
  firebase_performance: ^0.4.1
  firebase_remote_config: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/images/lp_image.png
    - assets/images/logo.png
    - assets/images/logo.jpg
    - assets/images/logofb.png
    - assets/images/lua-01.png
    - assets/images/lua-02.png
    - assets/images/lua-03.png
    - assets/images/lua-04.png
    - assets/images/lua-05.png
    - assets/images/lua-06.png
    - assets/images/lua-07.png
    - assets/images/lua-08.png
    - assets/images/lua-09.png
    - assets/images/lua-10.png
    - assets/images/lua-11.png
    - assets/images/lua-12.png
    - assets/images/lua-13.png
    - assets/images/lua-14.png
    - assets/images/lua-15.png
    - assets/images/lua-16.png
    - assets/images/lua-17.png
    - assets/images/lua-18.png
    - assets/images/lua-19.png
    - assets/images/lua-20.png
    - assets/images/lua-21.png
    - assets/images/lua-22.png
    - assets/images/lua-23.png
    - assets/images/lua-24.png
    - assets/images/lua-25.png
    - assets/images/lua-26.png
    - assets/images/lua-27.png
    - assets/images/lua-28.png
    - assets/images/lua-29.png
    - assets/images/f1.jpg
    - assets/images/f2.jpg
    - assets/images/f3.jpg
    - assets/images/f4.jpg
    - assets/images/f5.jpg
    - assets/images/f6.jpg
    - assets/images/ar.png
    - assets/images/aq.png
    - assets/images/ca.png
    - assets/images/cap.png
    - assets/images/es.png
    - assets/images/ge.png
    - assets/images/le.png
    - assets/images/li.png
    - assets/images/pe.png
    - assets/images/sa.png
    - assets/images/to.png
    - assets/images/vi.png
    - assets/images/ar-to.png
    - assets/images/aq-pe.png
    - assets/images/cap-aq.png
    - assets/images/ca-le.png
    - assets/images/es-sa.png
    - assets/images/ge-ca.png
    - assets/images/le-vi.png
    - assets/images/li-es.png
    - assets/images/pe-ar.png
    - assets/images/sa-ca.png
    - assets/images/to-ge.png
    - assets/images/vi-li.png
    - assets/images/icone1.png
    - assets/images/icone2.png
    - assets/images/icone3.png
    - assets/images/icone4.png
    - assets/images/icone5.png
    - assets/images/icone6.png
    - assets/images/fundo_diario.png
    - assets/images/fundodatas.png
module:
     androidX: true